version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - backend_net
    environment:
      - APP_ENV=local
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    container_name: laravel_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend_net
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend_net

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend_net

  mailpit:
    image: axllent/mailpit
    container_name: laravel_mailpit
    restart: unless-stopped
    ports:
      - "8026:8025"
    networks:
      - backend_net

volumes:
  db_data:

networks:
  backend_net:
    driver: bridge
